config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get 'users/new'
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, only: [:show, :edit, :update]
  resources :skills
end

app/models/user.rb
class User < ApplicationRecord
  has_many :skills
  before_save { email.downcase!}
  has_one_attached :avatar_image do |attachable|
    attachable.variant :display, resize_to_limit: [500, 500]
  end
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255},
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password        
  validates :password, presence: true, length: { minimum: 6}, allow_nil: true
  validates :introduce_messages, length: { minimum: 200, maximum: 799}
  validates :avatar_image, content_type: { in: %w[image/gif image/jpeg image/png],
                                           message: "には正しい形式を選択してください" },
                           size: { less_than: 5.megabytes,
                                   message: "は5MB以下にしてください" }
  # 渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)                                                  
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user
  before_action :correct_user
  def show
    @user = User.find(params[:id])

    @back_skills_2M_ago = Skill.where('category_id=?', 1)
                          .where(updated_at: ..Time.now.months_ago(2).end_of_month)
                          .order(updated_at: :desc).to_a.uniq { |n| n[:name] }
                          .pluck(:level).sum

    @back_skills_last_month = Skill.where('category_id=?', 1)
                              .where(updated_at: ..Time.now.months_ago(1).end_of_month)
                              .order(updated_at: :desc).to_a.uniq { |n| n[:name] }
                              .pluck(:level).sum

    @back_skills_this_month = Skill.where('category_id=?', 1)
                              .where(updated_at: ..Time.now.end_of_month)
                              .order(updated_at: :desc).to_a.uniq { |n| n[:name] }
                              .pluck(:level).sum


    @front_skills_2M_ago = Skill.where('category_id=?', 2)
                          .where(updated_at: ..Time.now.months_ago(2).end_of_month)
                          .order(updated_at: :desc).to_a.uniq { |n| n[:name] }
                          .pluck(:level).sum

    @front_skills_last_month = Skill.where('category_id=?', 2)
                              .where(updated_at: ..Time.now.months_ago(1).end_of_month)
                              .order(updated_at: :desc).to_a.uniq { |n| n[:name] }
                              .pluck(:level).sum

    @front_skills_this_month = Skill.where('category_id=?', 2)
                              .where(updated_at: ..Time.now.end_of_month)
                              .order(updated_at: :desc).to_a.uniq { |n| n[:name] }
                              .pluck(:level).sum


    @infra_skills_2M_ago = Skill.where('category_id=?', 3)
                          .where(updated_at: ..Time.now.months_ago(2).end_of_month)
                          .order(updated_at: :desc).to_a.uniq { |n| n[:name] }
                          .pluck(:level).sum

    @infra_skills_last_month = Skill.where('category_id=?', 3)
                              .where(updated_at: ..Time.now.months_ago(1).end_of_month)
                              .order(updated_at: :desc).to_a.uniq { |n| n[:name] }
                              .pluck(:level).sum

    @infra_skills_this_month = Skill.where('category_id=?', 3) 
                              .where(updated_at: ..Time.now.end_of_month)
                              .order(updated_at: :desc).to_a.uniq { |n| n[:name] }
                              .pluck(:level).sum

    @back_chart = [@back_skills_2M_ago, @back_skills_last_month, @back_skills_this_month]
    @front_chart = [@front_skills_2M_ago, @front_skills_last_month, @front_skills_this_month]
    @infra_chart = [@infra_skills_2M_ago, @infra_skills_last_month, @infra_skills_this_month]

    @months = [
      Date.today.months_ago(2).strftime("%B"),
      Date.today.last_month.strftime("%B"),
      Date.today.strftime("%B")]

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.avatar_image.attach(params[:user][:avatar_image]) if @user.avatar_image.blank?
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  private 

  def user_params 
    params.require(:user).permit(:introduce_messages, :avatar_image)
  end

  # beforeフィルタ
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url, status: :see_other) unless @user == current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% content_for :js do %>
  <%= javascript_import_module_tag "custom/image_upload" %>
<% end %>
<% provide(:title, "プロフィール編集") %>
<div class="page_title">
  <h1 id="profile_edit">自己紹介を編集する</h1>
</div>

<%= form_with(model: @user, class: "profile_edit", local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>
  
  <div class="profile">
    <div class="self-introduction">
      <div class="input">
        <%= f.label :introduce_messages, "自己紹介文" %>
        <%= f.text_area :introduce_messages, class: 'text-form-control', size: "40x5" %>
      </div>
      <p>200文字以上、800文字未満で入力してください</p>
    </div>
    <div class="img-upload">
      <%= f.label :avatar_image, "アバター画像" %>
      <%= f.label :avatar_image, "画像ファイルを添付する", class: "image_input_btn" %>
      <%= f.file_field :avatar_image, class: "image_form", accept: "image/jpeg,image/gif,image/png" %>
    </div>
  </div>

  <%= f.submit "自己紹介を確定する", class: "btn center-block" %>
<% end %>

app/views/users/show.html.erb
<% content_for :js do %>
  <%= javascript_import_module_tag "custom/bar_chart" %>
<% end %>
<div id="months" data-json="<%= @months.to_json %>"></div>
<div id="back_chart" data-json="<%= @back_chart.to_json %>"></div>
<div id="front_chart" data-json="<%= @front_chart.to_json %>"></div>
<div id="infra_chart" data-json="<%= @infra_chart.to_json %>"></div>
<div class="center">
  <div class="container">
    <div class="img">
      <%= image_tag @user.avatar_image.variant(:display) if @user.avatar_image.attached? %>
      <%= image_tag "85340511.png" unless @user.avatar_image.attached? %>
    </div>
    <div class="introduce">
      <h2><span>自己紹介</span></h2>
      <p class="real"><%= @user.introduce_messages %></p>
      <%= link_to "自己紹介を編集する", edit_user_path(@user), class: "btn" %>
    </div>
  </div>
  <div class="skillchart">
    <h2><span>スキルチャート</span></h2>
    <%= link_to "スキルを編集する", skills_path, class: "btn" %>
    <div class="chart">
      <div style="display: block; box-sizing: border-box; height: 500px; width: 1064px; margin-left: 20px;">
        <canvas id="myChart"></canvas>
      </div>
    </div>
  </div>
</div>