config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get 'users/new'
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, only: [:show, :edit, :update]
  resources :skills
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :user
  belongs_to :category
  validates :user_id, presence: true
  validates :category_id, presence: true
  validates :name, presence: true, length: { maximum: 30 }
  validates :level, presence: true
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: [:destroy]

  def index
    @user = User.find(session[:user_id])
    @categories = Category.all
    @skill = @user.skills.build
  end

  def new
    @name_params = params[:category_name]
    @id_params = params[:category_id]
    @user = User.find(session[:user_id])
    @skill = current_user.skills.build if logged_in?
  end

  def create
    @user = User.find(session[:user_id])
    @skill = current_user.skills.build(skill_params)
    if @skill.save
      flash[:notice] = "#{@skill.category.name}に#{@skill.name}を習得レベル#{@skill.level}で追加しました！"
      redirect_to skills_url
    else
      render 'skills/new', status: :unprocessable_entity
    end
  end

  def update
    @user = User.find(session[:user_id])
    @skill = current_user.skills.find(params[:id])
    if @skill.update!(skill_params)
      flash[:success] = "#{@skill.name}の習得レベルを保存しました！"
      redirect_to skills_url
    else
    end
  rescue ActiveRecord::RecordInvalid => e  
    flash[:danger] = "習得レベルの保存に失敗しました。#{e.message}"
    render 'skills/index', status: :unprocessable_entity
  end

  def destroy
    @user = User.find(session[:user_id])
    @skill = @user.skills.find(params[:id])
    @skill.destroy
    flash[:danger] = "#{@skill.name}の項目を削除しました！"
    redirect_to skills_url, status: :see_other
  end

  private

    def skill_params
      params.require(:skill).permit(:name, :level, :category_id)
    end

    def correct_user
      @skills = current_user.skills.find_by(id: params[:id])
      redirect_to root_url, status: :see_other if @skills.nil?
    end

    def between_this_month(skill)
      skill.updated_at.between?(Time.current.beginning_of_month, Time.current.end_of_month)
    end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/index.html.erb
<% provide(:title, "スキル編集") %>

<% content_for :modal_success do %>
  <h3><%= flash[:success] %></h3>
<% end %>

<% content_for :modal_danger do %>
  <h3><%= flash[:danger] %></h3>
<% end %>

<% content_for :modal_notice do %>
  <h3><%= flash[:notice] %></h3>
<% end %>

<section id="modalArea" class="modalArea">
  <div class="modalBg"></div>
  <div class="modalWrapper">
    <div class="modalContents">
      <% if flash[:success].present? %>
        <%= yield(:modal_success) %>
      <% end %>
      <% if flash[:danger].present? %>
        <%= yield(:modal_danger) %>
      <% end %>
      <% if flash[:notice].present? %>
        <%= yield(:modal_notice) %>
      <% end %>
    </div>
    <div id="closeModal" class="closeModal">
      <button>スキル編集ページに戻る</button>
    </div>
  </div>
</section>

<div class="skill-index">
  <% @categories.each do |category| %>
    <div class="panel panel-default">
      <div class="panel-body">
        <h3><%= category.name %></h3>
        <%= link_to "スキルを追加する", 
            new_skill_path(category_name: category.name, 
                            category_id: category.id), class: "skill-add" %>
      </div>
      <% unless category.skills.empty? %>
        <table class="table">
          <div class="thead">
            <tr>
              <th class="th-name">習得スキル</th>
              <th class="th-level">習得レベル</th>
            </tr>
          </div>
          <% category.skills.each do |skill| %>
            <div class="tbody">
              <tr>
                <% if skill.updated_at.between?(Time.current.beginning_of_month, Time.current.end_of_month)%>
                  <th style="vertical-align: middle" class="th-name"><%= skill.name %></th>
                  <%= form_with(model: skill, method: "patch", local: true) do |f| %>
                    <th style="vertical-align: middle" class="th-level">
                      <%= f.select :level, (1..100), { selected: "#{skill.level}" }, class: "level-number", id: "skill_level_#{skill.id}" %>
                      <i class="fa-solid fa-caret-down"></i>
                    </th>
                    <th style="vertical-align: middle" class="th-save">
                      <%= f.submit "習得レベルを保存する", class: "level-save" %>
                    </th>
                  <% end %>
                  <th style="vertical-align: middle" class="th-delete">
                    <%= button_to "スキルを削除する", skill_path(skill.id), method: :delete, class: 'level-delete' %>
                  </th>
                <% else %>
                  <% if !category.skills.group(:name).count.to_a.select { |skill| skill[1] >= 2 }.any? %> 
                    <th style="vertical-align: middle" class="th-name"><%= skill.name %></th>
                    <%= form_with(model: @skill, method: "post") do |f| %>
                      <th style="vertical-align: middle" class="th-level">
                        <%= f.select :level, (1..100), { selected: "#{skill.level}" }, class: "level-number", id: "skill_level_#{skill.id}" %>
                        <i class="fa-solid fa-caret-down"></i>
                      </th>
                        <%= f.hidden_field :name, :value => skill.name %>
                        <%= f.hidden_field :category_id, :value => skill.category_id %>
                      <th style="vertical-align: middle" class="th-save">
                        <%= f.submit "習得レベルを保存する", class: "level-save" %>
                      </th>
                    <% end %>
                    <th style="vertical-align: middle" class="th-delete">
                      <%= button_to "スキルを削除する", skill_path(skill.id), method: :delete, class: 'level-delete' %>
                    </th>
                  <% end %>
                <% end %>
              </tr>
            </div>
          <% end %>
        </table>
      <% end %>
    </div>
  <% end %>
</div>

app/views/skills/new.html.erb
<% provide(:title, "スキル追加") %>

<div class="skill container">
  <h1><%= @name_params %>にスキルを追加</h1>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_with(model: @skill, local: true) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name, "習得スキル名" %>
        <%= f.text_field :name, class: 'self-form-control' %>

        <div class="level-new-group">
          <%= f.label :level, "習得レベル" %>
          <%= f.select :level, (1..100), {},
                                     class: 'self-form-control level-new' %>
          <i class="fa-solid fa-caret-down"></i>
          <p>0~100の間で選択してください</p>
        </div>

        <%= f.hidden_field :category_id, value: "#{@id_params}" %>
        <%= f.submit "追加する", class: "btn btn-lg center-block"%>
      <% end %>
    </div>
  </div>
</div>