config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get 'users/new'
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users, only: [:show, :edit, :update]
  resources :skills
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<% if logged_in? %>
  <h4><%= current_user.name %> portfolio site</h4>
<% else %>
  <h4>user name's portfolio site</h4>
<% end %>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top" style="background-color: #1B5678">
  <div class="container-fluid">
    <% if logged_in? %>
    <%= link_to "My Portfolio", user_path(@user), id: "app_name" %>
    <% else %>
      <%= link_to "My Portfolio", root_path, id: "app_name" %>
    <% end %>
    <% if logged_in? %>
      <%= button_to "ログアウト", logout_path, method: :delete,
          class: "btn btn-lg" %>
    <% else %>
      <%= link_to "ログイン", login_path, class: "btn btn-lg btn-default",
        id: "btn" %>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="utf-8">
  
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_importmap_tags %>
    <%= yield(:js) %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 

    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.3.0/dist/chart.umd.min.js"></script>
    <script src="https://kit.fontawesome.com/d19857391e.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="main container">
      <% if flash[:success].present? || flash[:danger].present? || flash[:notice].present? %>
        <script>
          window.addEventListener('DOMContentLoaded', function() {
            var modalArea = document.getElementById('modalArea');
            if (modalArea) {
              modalArea.style.display = 'block';
            }
          var closeModal = document.getElementById('closeModal');
          closeModal.addEventListener('click', function(){
            modalArea.style.display = 'none';
          });
          });
        </script>
      <% end %>
      <%= yield %>
    </div>
    <%= debug(params) if Rails.env.development? %>
    <%= render 'layouts/footer' %>
  </body>
</html>